module.exports = {
	printWidth: 80,
	tabWidth: 2,
	useTabs: false,
	semi: true,
	singleQuote: false,
	jsxSingleQuote: false,
	quoteProps: "as-needed",
	trailingComma: "none",
	bracketSpacing: true,
	jsxBracketSameLine: false,
	arrowParens: "avoid",
	requirePragma: false,
	insertPragma: false,
	proseWrap: "never",
	htmlWhitespaceSensitivity: "css",
	vueIndentScriptAndStyle: false,
	endOfLine: "lf",
	embeddedLanguageFormatting: "auto"
}
